name: esmologs
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - python~=3.10
  - pip
  - setuptools>=60.7
  - pytest~=7.4.2
  - pytest-datadir~=1.4.1
  - mafft~=7.505
  - pyhmmer~=0.10.2
  - hmmer~=3.3.2
  - psutil
  - foldseek
  - numpy~=1.25.2
  - pytorch-cuda~=11.7
  - pytorch~=2.0.1
  - tqdm
  - biopython~=1.79
  - seaborn
  - hhsuite
  - scipy~=1.11.2
  - pip:
    - fair-esm
    - -e .
