name: esmologs
channels:
  - defaults
  - bioconda
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python~=3.9
  - pip
  - setuptools>=60.7
  - pytest~=7.0.1
  - pytest-datadir~=1.3.1
  - mafft~=7.505
  - pyhmmer~=0.6.0
  - coverage~=6.3.2
  - hmmer~=3.3.2
  - psutil
  - foldseek
  - numpy~=1.23.0
  - pytorch-cuda~=11.6
  - pytorch
  - tqdm
  - biopython~=1.79
  - seaborn
  - hhsuite
  - scipy
  - pip:
    - fair-esm
    - -e .
